### ISSUE TITLE
Delete Questions from Database when User Delete his Polls.

### ISSUE THREAD

**Issue by nil1729** [nil1729/poll-app#3]
Now User can Delete their Polls, but questions of these polls didn't delete. So Implement a Function or Logic to do so.

**Comment by jacklagare** [comment]
Hi! I want to work on this. 

May I know which file contains the **delete poll** functionality? I was looking at `survey.js` and I couldn't see it.

**Comment by nil1729** [comment]
HI @jacklagare. The file containing the `Delete` Survey is on `user.js` file on `routes` directory. See [here](https://github.com/nil1729/poll-app/blob/master/routes/user.js) the last API is for `Delete`.

**Comment by nil1729** [comment]
If you want to work on this issue. Then you have to set up a config file that contains all necessary environment variables. Create a file named `default.json` on the `config` directory. You can test it by your own credentials or simply drop a mail, I will send you the test credentials. 
Thank you.

**Comment by jacklagare** [comment]
Please send me the list of environment variables and the structure of `default.json`.

**Comment by nil1729** [comment]
Hi, @jacklagare. I set up the `README` and provide necessary tutorials for Creating Credentials.
Thanks.

**Comment by jacklagare** [comment]
Awesome! Thanks!

**Comment by jacklagare** [comment]
PR created.

**Comment by nil1729** [comment]
You didn't open a PR yet.

**Comment by jacklagare** [comment]
Sorry about that. Here is the PR. #6

**Comment by nil1729** [comment]
Thanks a lot for your Contribution. :smile: 
I merged your PR.
